# -*- coding: utf-8 -*-
"""lap1-week1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zG5PZgBLGbnCAa2cB1z4W6n2bkh6LhH
"""

print("Welcome to Python Programming!")
print("Nasayem Alqahtani")
print("Python Programming")

student_name = "Alice"
age = 20
gpa = 3.75
subjects = ["Math", "Python", "Physics"]
student_info = {"id": 101, "year": 2}
skills = {"Python", "SQL"}
is_enrolled = True
graduation_date = None

print(student_name, type(student_name))
print(age, type(age))
print(gpa, type(gpa))
print(subjects, type(subjects))
print(student_info, type(student_info))
print(skills, type(skills))
print(is_enrolled, type(is_enrolled))
print(graduation_date, type(graduation_date))